/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdIndexRouteImport } from './routes/course.$courseId.index'
import { Route as CourseCourseIdItemIdStepIdRouteImport } from './routes/course.$courseId.$itemId.$stepId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdIndexRoute = CourseCourseIdIndexRouteImport.update({
  id: '/course/$courseId/',
  path: '/course/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdItemIdStepIdRoute =
  CourseCourseIdItemIdStepIdRouteImport.update({
    id: '/course/$courseId/$itemId/$stepId',
    path: '/course/$courseId/$itemId/$stepId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/$itemId/$stepId': typeof CourseCourseIdItemIdStepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/course/$courseId/$itemId/$stepId': typeof CourseCourseIdItemIdStepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/$itemId/$stepId': typeof CourseCourseIdItemIdStepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/course/$courseId/' | '/course/$courseId/$itemId/$stepId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/course/$courseId' | '/course/$courseId/$itemId/$stepId'
  id:
    | '__root__'
    | '/'
    | '/course/$courseId/'
    | '/course/$courseId/$itemId/$stepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseCourseIdIndexRoute: typeof CourseCourseIdIndexRoute
  CourseCourseIdItemIdStepIdRoute: typeof CourseCourseIdItemIdStepIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/': {
      id: '/course/$courseId/'
      path: '/course/$courseId'
      fullPath: '/course/$courseId/'
      preLoaderRoute: typeof CourseCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/$itemId/$stepId': {
      id: '/course/$courseId/$itemId/$stepId'
      path: '/course/$courseId/$itemId/$stepId'
      fullPath: '/course/$courseId/$itemId/$stepId'
      preLoaderRoute: typeof CourseCourseIdItemIdStepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseCourseIdIndexRoute: CourseCourseIdIndexRoute,
  CourseCourseIdItemIdStepIdRoute: CourseCourseIdItemIdStepIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
