/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdIndexRouteImport } from './routes/course.$courseId.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as CourseCourseIdItemIdStepIdRouteImport } from './routes/course.$courseId.$itemId.$stepId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdIndexRoute = CourseCourseIdIndexRouteImport.update({
  id: '/course/$courseId/',
  path: '/course/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdItemIdStepIdRoute =
  CourseCourseIdItemIdStepIdRouteImport.update({
    id: '/course/$courseId/$itemId/$stepId',
    path: '/course/$courseId/$itemId/$stepId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/$itemId/$stepId': typeof CourseCourseIdItemIdStepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/course/$courseId/$itemId/$stepId': typeof CourseCourseIdItemIdStepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/$itemId/$stepId': typeof CourseCourseIdItemIdStepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/signup'
    | '/api/auth/$'
    | '/course/$courseId/'
    | '/course/$courseId/$itemId/$stepId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/signup'
    | '/api/auth/$'
    | '/course/$courseId'
    | '/course/$courseId/$itemId/$stepId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/signup'
    | '/api/auth/$'
    | '/course/$courseId/'
    | '/course/$courseId/$itemId/$stepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CourseCourseIdIndexRoute: typeof CourseCourseIdIndexRoute
  CourseCourseIdItemIdStepIdRoute: typeof CourseCourseIdItemIdStepIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/': {
      id: '/course/$courseId/'
      path: '/course/$courseId'
      fullPath: '/course/$courseId/'
      preLoaderRoute: typeof CourseCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/$itemId/$stepId': {
      id: '/course/$courseId/$itemId/$stepId'
      path: '/course/$courseId/$itemId/$stepId'
      fullPath: '/course/$courseId/$itemId/$stepId'
      preLoaderRoute: typeof CourseCourseIdItemIdStepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CourseCourseIdIndexRoute: CourseCourseIdIndexRoute,
  CourseCourseIdItemIdStepIdRoute: CourseCourseIdItemIdStepIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
